# Generated by Django 5.1.2 on 2024-12-30 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_category_course_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.category'),
        ),
    ]
