# Generated by Django 5.1.2 on 2025-01-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer',
            new_name='correctAnswer',
        ),
    ]
