# Generated by Django 5.1.2 on 2025-01-03 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_category_image'),
        ('tests', '0002_rename_correct_answer_question_correctanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='course',
        ),
        migrations.AddField(
            model_name='test',
            name='lesson',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='courses.lesson'),
            preserve_default=False,
        ),
    ]
